BEGIN;

CREATE TABLE IF NOT EXISTS chats
(
    id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    createdBy VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS links
(
    id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "value"   VARCHAR(400) NOT NULL,
    hashsum INT
);

CREATE TABLE IF NOT EXISTS chat_links
(
    id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    chat_id BIGINT REFERENCES chats(id),
    link_id BIGINT REFERENCES links(id)
);

COMMIT;
