app:
  scheduler:
    update-interval: 30s
    delete-interval: 4h

spring:
  application:
    name: scrapper

  datasource:
    url: jdbc:postgresql://localhost:5435/db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui
  server:
    port: 8081

logging:
  config: classpath:log4j2-plain.xml
